name: example
description: Counter example using the ViewModelBinder package and the ViewModelBinder architecture
version: 1.0.0
homepage: https://github.com/zaiste/ViewModelBinder

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  view_model_binder:
    path: ../

  rxdart: ^0.27.0

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
